/* eslint-disable */
//  WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_YrTFT7ioU",
    "oauth": {
        "domain": "kpamplify.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "email",
            "openid",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://master.dj464q5nsb6u9.amplifyapp.com/",
        "redirectSignOut": "https://master.dj464q5nsb6u9.amplifyapp.com/",
        "responseType": "token",
        "client_id": "7q7b07hv878lo6vp8qma7oclqj"
    }
};


export default awsmobile;
